"""empty message

Revision ID: 07983e8403ac
Revises: e16a4d3b5703
Create Date: 2023-03-01 22:38:14.529694

"""
from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes
from sqlmodel import SQLModel
import models  # Loading the models into SQLModel.metadata

# revision identifiers, used by Alembic.
revision = '07983e8403ac'
down_revision = 'e16a4d3b5703'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projectlike', type_='foreignkey')
    op.create_foreign_key(None, 'projectlike', 'user', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projectlike', type_='foreignkey')
    op.create_foreign_key(None, 'projectlike', 'project', ['sender_id'], ['id'])
    # ### end Alembic commands ###
