"""empty message

Revision ID: e16a4d3b5703
Revises: 6b1eb16b25b8
Create Date: 2023-03-01 22:14:41.348097

"""
from alembic import op
import sqlalchemy as sa

import sqlmodel.sql.sqltypes
from sqlmodel import SQLModel
import models  # Loading the models into SQLModel.metadata

# revision identifiers, used by Alembic.
revision = 'e16a4d3b5703'
down_revision = '6b1eb16b25b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('user', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
